- type: rank
  id: RatRankWorkerSenior
  name: Старший Рабочий
  prefix: Ст. Рабочий
  paygrade: Е3

- type: rank
  id: RatRankWorkerMiddle
  name: Рабочий
  prefix: Рабочий
  paygrade: Е2

- type: rank
  id: RatRankWorkerJunior
  name: Рядовой Рабочий
  prefix: Ряд. Рабочий
  paygrade: Е1