- type: rank
  id: RatRankKommissarSenior
  name: Старший комиссар
  prefix: Ст. Комиссар
  paygrade: О5

- type: rank
  id: RatRankKommissarMiddle
  name: Комиссар
  prefix: Комиссар
  paygrade: О4

- type: rank
  id: RatRankKommissarJunior
  name: Младший Комиссар
  prefix: Мл. Комиссар
  paygrade: О3

