- type: rank
  id: RatRankCommandantSenior
  name: Гененерал-полковник
  prefix: Гененерал-полк.
  paygrade: О6

- type: rank
  id: RatRankCommandantMiddle
  name: Гененерал-лейтенант
  prefix: Гененерал-лейт.
  paygrade: О5

- type: rank
  id: RatRankCommandantJunior
  name: Гененерал-майор
  prefix: Гененерал-майор
  paygrade: О4

