- type: rank
  id: RatRankOverbossSenior
  name: Старший Координатор
  prefix: Ст. Координатор
  paygrade: О3

- type: rank
  id: RatRankOverbossMiddle
  name: Координатор
  prefix: Координатор
  paygrade: О2

- type: rank
  id: RatRankOverbossJunior
  name: Младший Координатор
  prefix: Мл. Координатор
  paygrade: О1