- type: rank
  id: RatRankDoctorSenior
  name: Фельдшер
  prefix: Фельдшер
  paygrade: Е5

- type: rank
  id: RatRankDoctorMiddle
  name: Старший Санитар
  prefix: Ст. Санитар
  paygrade: E4

- type: rank
  id: RatRankDoctorJunior
  name: Санитар
  prefix: Санитар
  paygrade: E3

