- type: rank
  id: RatRankDirectorSenior
  name: Капитан Врач
  prefix: Кап. Врач
  paygrade: О3

- type: rank
  id: RatRankDirectorMiddle
  name: Капитан-лейтенант Врач
  prefix: Кап.-лейт. Врач
  paygrade: О2

- type: rank
  id: RatRankDirectorJunior
  name: Лейтенант Врач
  prefix: Лейт. Врач
  paygrade: О1