- type: rank
  id: RatRankMVDOfficerSenior
  name: Сержант Милиции
  prefix: Сер. Милиционер
  paygrade: E3

- type: rank
  id: RatRankMVDOfficerMiddle
  name: Старший Милиционер
  prefix: Ст. Милиционер
  paygrade: E2

- type: rank
  id: RatRankMVDOfficerJunior
  name: Милиционер
  prefix: Милиционер
  paygrade: E1

