- type: rank
  id: RatRankTaskmasterSenior
  name: Главный техник
  prefix: Глав. техник
  paygrade: Е8

- type: rank
  id: RatRankTaskmasterMiddle
  name: Мастер-техник
  prefix: Мас.-техник
  paygrade: Е7

- type: rank
  id: RatRankTaskmasterJunior
  name: Старший техник
  prefix: Ст. техник
  paygrade: Е6