- type: rank
  id: RatRankMVDGruntSenior
  name: Старший помощник	
  prefix: Ст. помощник	
  paygrade: О3

- type: rank
  id: RatRankMVDGruntMiddle
  name: Помощник
  prefix: Помощник
  paygrade: О2

- type: rank
  id: RatRankMVDGruntJunior
  name: Младший помощник
  prefix: Мл. помощник
  paygrade: О1

