- type: rank
  id: RatRankArtificerSenior
  name: Старший Исследователь
  prefix: Ст. Исследователь
  paygrade: Е5

- type: rank
  id: RatRankArtificerMiddle
  name: Исследователь
  prefix: Исследователь
  paygrade: Е4

- type: rank
  id: RatRankArtificerJunior
  name: Младший Исследователь
  prefix: Мл. Исследователь
  paygrade: Е3