- type: rank
  id: RatRankFleetkapitanSenior
  name: Капитан флота
  prefix: Кап. флота
  paygrade: О3

- type: rank
  id: RatRankFleetkapitanMiddle
  name: Капитан-лейтенант флота
  prefix: Кап.-лейт. флота
  paygrade: О2

- type: rank
  id: RatRankFleetkapitanJunior
  name: Лейтенант флота
  prefix: Лейт. флота
  paygrade: О1