- type: rank
  id: RatRankPartisanHead
  name: Старший Сержант Ополченец
  prefix: Ст. Серж. Ополченец
  paygrade: Е5

- type: rank
  id: RatRankPartisanLead
  name: Сержант Ополченец
  prefix: Серж. Ополченец
  paygrade: Е4

- type: rank
  id: RatRankPartisanSenior
  name: Младшний Сержант Ополченец
  prefix: Мл. Серж. Ополченец
  paygrade: Е3

- type: rank
  id: RatRankPartisanMiddle
  name: Ефрейтор Ополченец
  prefix: Ефр. Ополченец
  paygrade: Е2

- type: rank
  id: RatRankPartisanJunior
  name: Рядовой Ополченец
  prefix: Ряд. Ополченец
  paygrade: Е1