- type: rank
  id: RatRankDockhandSenior
  name: Бригадир Грузчик
  prefix: Бриг. Грузчик
  paygrade: Е3

- type: rank
  id: RatRankkDockhandMiddle
  name: Старший Грузчик
  prefix: Ст. Грузчик
  paygrade: Е2

- type: rank
  id: RatRankkDockhandJunior
  name: Грузчик
  prefix: Грузчик
  paygrade: Е1