- type: rank
  id: RatRankForemanSenior
  name: Бригадир
  prefix: Бригадир
  paygrade: Н3

- type: rank
  id: RatRankForemanMiddle
  name: Интендант
  prefix: Интендант
  paygrade: Н2

- type: rank
  id: RatRankForemanJunior
  name: Надзиратель
  prefix: Надзиратель
  paygrade: Н1