- type: rank
  id: RatRankLevymanHead
  name: Легат
  prefix: Легат
  paygrade: Л5

- type: rank
  id: RatRankLevymanLead
  name: Центурион
  prefix: Центурион
  paygrade: Л4

- type: rank
  id: RatRankLevymanSenior
  name: Трибун
  prefix: Трибун
  paygrade: Л3

- type: rank
  id: RatRankLevymanMiddle
  name: Проктор
  prefix: Проктор
  paygrade: Л2

- type: rank
  id: RatRankLevymanJunior
  name: Леви
  prefix: Леви
  paygrade: Л1