- type: rank
  id: RatRankSurgeonSenior
  name: Магус
  prefix: Магус
  paygrade: М3

- type: rank
  id: RatRankSurgeonMiddle
  name: Префект
  prefix: Префект
  paygrade: М2

- type: rank
  id: RatRankSurgeonJunior
  name: Инициат
  prefix: Инициат
  paygrade: М1